config/routes.rb
# frozen_string_literal: true

Hecms::Engine.routes.draw do
  devise_for :users, path: 'auth/users', class_name: 'Hecms::User', module: :devise, controllers: {
    sessions: 'hecms/auth/sessions',
    passwords: 'hecms/auth/passwords'
  }

  root to: 'categories#index'

  resources :categories
  resources :articles
  resources :tags

  resources :pictures, only: [:create]
  resources :uploads, only: [:create]
  resources :locales, only: [:update]
end

app/models/hecms/application_record.rb
# frozen_string_literal: true

module Hecms
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
    extend KeywordLikeHelper
  end
end

app/models/hecms/article.rb
# frozen_string_literal: true

module Hecms
  class Article < ApplicationRecord
    include SoftDelete
    extend Enumerize

    has_one_attached :image

    acts_as_tenant(:user)

    has_many :category_relations, as: :record, inverse_of: :record
    has_many :categories, through: :category_relations, class_name: 'Category'

    has_many :tag_relations, as: :record, inverse_of: :record
    has_many :tags, through: :tag_relations

    accepts_nested_attributes_for :category_relations, reject_if: :all_blank, allow_destroy: true
    accepts_nested_attributes_for :tag_relations, reject_if: :all_blank, allow_destroy: true

    scope_keyword_like hecms_articles: [:title]

    EDITERS = { editer1: 1, editer2: 2, editer3: 3, editer4: 4, editer5: 5 }.freeze

    enumerize :editer_id, in: EDITERS, default: :editer1, i18n_scope: 'activerecord.attributes.article/editer_id'

    def category_names
      categories.map(&:name).join(' ')
    end

    def tag_names
      tags.map(&:name).join(' ')
    end

    def display_created_at_date
      I18n.l(created_at, format: '%Y-%m-%d %H:%M:%S')
    end

    def display_published_date
      I18n.l(published_date, format: '%Y-%m-%d %H:%M:%S')
    end

    def image_thumb_url(process)
      image.service_url(params: { 'x-oss-process' => process })
    end
  end
end

app/models/hecms/category.rb
# frozen_string_literal: true

module Hecms
  class Category < ApplicationRecord
    acts_as_nested_set
    include SoftDelete
    extend FriendlyId

    has_many :category_relations, dependent: :destroy
    has_many :articles, through: :category_relations, source: :record, source_type: 'Article'
    has_many :tags, through: :category_relations, source: :record, source_type: 'Tag'

    friendly_id :slug, use: :slugged

    def self.options_for_select
      options = []
      roots.each do |category|
        each_with_level(category.self_and_descendants) do |x, level|
          options << ["#{'-' * level} #{x.name}", x.id]
        end
      end
      options
    end
  end
end

app/models/hecms/category_relation.rb
# frozen_string_literal: true

module Hecms
  class CategoryRelation < ApplicationRecord
    belongs_to :record, polymorphic: true, touch: true
    belongs_to :category
  end
end

app/models/hecms/picture.rb
# frozen_string_literal: true

module Hecms
  class Picture < ApplicationRecord
    has_one_attached :image
  end
end

app/models/hecms/tag.rb
# frozen_string_literal: true

module Hecms
  class Tag < ApplicationRecord
    extend FriendlyId

    has_many :tag_relations
    has_many :articles, through: :tag_relations, source: :record, source_type: 'Article'

    accepts_nested_attributes_for :tag_relations, reject_if: :all_blank, allow_destroy: true

    friendly_id :slug, use: :slugged

    validates :name, presence: true

    scope_keyword_like hecms_tags: [:name]

    def self.options_for_select
      options = []
      all.each do |x|
        options << [x.name, x.id]
      end
      options
    end
  end
end

app/models/hecms/tag_relation.rb
# frozen_string_literal: true

module Hecms
  class TagRelation < ApplicationRecord
    belongs_to :record, polymorphic: true, touch: true
    belongs_to :tag, counter_cache: :articles_count
  end
end

app/models/hecms/user.rb
# frozen_string_literal: true

module Hecms
  class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable, :registerable
    devise :database_authenticatable,
           :recoverable, :rememberable, :validatable
  end
end

app/controllers/hecms/application_controller.rb
# frozen_string_literal: true

module Hecms
  class ApplicationController < ActionController::Base
  end
end

app/controllers/hecms/articles_controller.rb
# frozen_string_literal: true

require_dependency 'hecms/base_controller'

module Hecms
  class ArticlesController < BaseController
    before_action :find_article, only: %i[edit update show destroy]

    def index
      @articles = Article.keyword_like(params[:keyword]).includes(:tags, :categories).page(params[:page])
    end

    def search
      @articles = Article.keyword_like(params[:keyword]).includes(:tags, :categories).page(params[:page])
    end

    def new
      @article = Article.new
    end

    def edit; end

    def update
      if @article.update(form_params)
        flash[:notice] = t('common.update_success')
        redirect_to(articles_path)
      else
        flash[:alert] = t('common.update_fail')
        render(:new)
      end
    end

    def create
      @article = Article.new(form_params)
      if @article.save
        flash[:notice] = t('common.create_success')
        redirect_to(articles_path)
      else
        flash[:alert] = t('common.create_fail')
        render(:new)
      end
    end

    def destroy
      respond_to do |format|
        if @article.destroy
          format.html { redirect_to articles_path }
          format.json { render json: { code: 1111, id: @article.id } }
        else
          format.html { redirect_to articles_path }
          format.json { render json: { code: 0o000, id: nil } }
        end
      end
    end

    private

    def find_article
      @article = Article.find(params[:id])
    end

    def set_ui
      super
      @ui_main_nav_active_articles = 'active'
    end

    def form_params
      params.require(:article).permit(
        :image,
        :title,
        :seo_title,
        :keywords,
        :description,
        :content_html,
        :sort,
        :published_date,
        :top,
        :editer_id,
        :scheduled,
        category_ids: [],
        tag_ids: []
      )
    end
  end
end

app/controllers/hecms/base_controller.rb
# frozen_string_literal: true

require_dependency 'hecms/application_controller'

module Hecms
  class BaseController < ApplicationController
    layout 'layouts/hecms/application'
    before_action :authenticate_user!

    set_current_tenant_through_filter
    before_action :set_tenant

    def set_tenant
      set_current_tenant(current_user)
    end
  end
end

app/controllers/hecms/categories_controller.rb
# frozen_string_literal: true

require_dependency 'hecms/base_controller'

module Hecms
  class CategoriesController < BaseController
    before_action :find_category, only: %i[destroy edit update]

    def index
      @categories = Category.roots.page(params[:page])
    end

    def new
      @category = Category.new
    end

    def edit; end

    def update
      if @category.update(form_params)
        flash[:notice] = t('common.update_success')
        redirect_to(categories_path)
      else
        flash[:alert] = t('common.update_fail')
        render(:edit)
      end
    end

    def create
      @category = Category.new(form_params)

      if @category.save
        flash[:notice] = t('common.create_success')
        redirect_to(categories_path)
      else
        flash[:alert] = t('common.create_fail')
        render(:new)
      end
    end

    def destroy
      if @category.destroy
        flash[:notice] = t('common.delete_success')
        redirect_to(adm_categories_path)
      else
        flash[:alert] = t('common.delete_fail')
        redirect_to(adm_categories_path)
      end
    end

    private

    def find_category
      @category = Category.friendly.find(params[:id])
    end

    def set_ui
      super
      @ui_main_nav_active_categories = 'active'
    end

    def form_params
      params.require(:category).permit(
        :name,
        :parent_id,
        :pinyin,
        :seo_title,
        :keywords,
        :description,
        :enabled,
        :slug
      )
    end
  end
end

app/controllers/hecms/tags_controller.rb
# frozen_string_literal: true

require_dependency 'hecms/base_controller'

module Hecms
  class TagsController < BaseController
    before_action :find_tag, only: %i[destroy edit update]

    def index
      @tags = Tag.keyword_like(params[:keyword]).order(id: :desc).page(params[:page])
      # html = render_to_string action: :index, layout: false, formats: [:html]
    end

    def new
      @tag = Tag.new
    end

    def edit; end

    def update
      if @tag.update(form_params)
        flash[:notice] = t('common.update_success')
        redirect_to(tags_path, notice: '更新成功')
      else
        flash[:alert] = t('common.update_fail')
        render(:edit)
      end
    end

    def create
      @tag = Tag.new(form_params)
      if @tag.save
        flash[:notice] = t('common.create_success')
        redirect_to(tags_path)
      else
        flash[:alert] = t('common.create_fail')
        render(:new)
      end
    end

    def destroy
      if @tag.destroy
        flash[:notice] = t('common.delete_success')
        redirect_to(tags_path)
      else
        flash[:alert] = t('common.delete_fail')
        redirect_to(tags_path)
      end
    end

    private

    def find_tag
      @tag = Tag.find(params[:id])
    end

    def set_ui
      super
      @ui_main_nav_active_tags = 'active'
    end

    def form_params
      params.require(:tag).permit(
        :name,
        :pinyin,
        :seo_title,
        :keywords,
        :description,
        :slug
      )
    end
  end
end

app/controllers/hecms/uploads_controller.rb
# frozen_string_literal: true

require_dependency 'hecms/base_controller'

module Hecms
  class UploadsController < BaseController
    def create
      picture = Picture.new(image: params[:upload])
      if picture.save
        render(json: { url: picture.image.service_url })
      else
        render(json: {})
      end
    end
  end
end

app/helpers/hecms/application_helper.rb
# frozen_string_literal: true

module Hecms
  module ApplicationHelper
    def controller_path_action_name
      "#{controller.controller_path.gsub('/', '__')}__#{controller.action_name}"
    end

    def html_body_classes
      "#{controller_path_action_name} #{@body_classes&.join(' ')}"
    end

    def site_logo_url
      # SystemConfig.current.site_logo.service_url
      '/'
    end

    def site_name
      'Site Name'
    end

    def page_seo_title
      'Seo Title'
    end

    def page_keywords
      'Keywords'
    end

    def page_description
      'Description'
    end

    def slogan
      'Slogan'
    end

    def media_image_url(media_name)
      media_name = truncate(media_name, length: 7, omission: '')
      string = Base64.urlsafe_encode64(media_name)
      "https://prmedia.oss-cn-shanghai.aliyuncs.com/default_fff.png?x-oss-process=image/resize,w_300,h_300/watermark,image_bG9nb3cucG5nP3gtb3NzLXByb2Nlc3M9aW1hZ2UvcmVzaXplLFBfMTU=,g_nw,x_10,y_10/watermark,text_#{string},color_333333,shadow_50,t_100,g_center/watermark,text_5b6u5YWJ572R5aqS,color_666666,size_13,g_se"
    end

    def ui_right_floated_new_button_class
      'ui right floated basic button'
    end

    def ui_show_button_class
      'ui tiny basic button'
    end

    def ui_edit_button_class
      'ui tiny button'
    end

    def ui_delete_button_class
      'ui tiny inverted red button'
    end

    def ui_restore_button_class
      'ui basic tiny green button'
    end

    def ui_show_table_class
      'ui definition table'
    end

    def display_short_date(x)
      date = x.published_date || x.created_at
      I18n.l(date, format: :yueri)
    end

    def highlight(text)
      text = escape_once(strip_tags(text)).gsub('[h]', '<em>').gsub('[/h]', '</em>').gsub(/\\n|\\r/, '')
      text.html_safe
    end

    def title_tag
      @page_title.present? ? content_tag(:title, "#{site_name}_#{@page_title}") : content_tag(:title, "#{site_name}_#{page_seo_title}")
    end

    def keywords_tag
      @page_keywords.present? ? @page_keywords : page_keywords
    end

    def description_tag
      @page_description.present? ? @page_description : page_description
    end
  end
end

app/helpers/hecms/articles_helper.rb
module Hecms
  module ArticlesHelper
  end
end

app/helpers/hecms/categories_helper.rb
module Hecms
  module CategoriesHelper
  end
end

app/helpers/hecms/tags_helper.rb
module Hecms
  module TagsHelper
  end
end

app/views/hecms/application/_ckeditor_init.html.slim
= javascript_include_tag "/ckeditor/ckeditor.js"
css:
  .picture-form {
    display: none;
  }
  a.cke_dialog_tab {
    display: inline-block !important;
  }
  .cke_dialog_ui_file {
    display: none !important;
  }


.picture-form
  = form_for Picture.new, url: pictures_url, remote: true do |f|
    = f.file_field :image
    = f.submit "", class: 'js-picture-submit'

script:
  function checkUploadButton(selector) {
    if ($(selector).length != 0) {
        uploadImage(selector)
        return
    }
    setTimeout(function () {
        checkUploadButton(selector)
    }, 1000);
  }

  function uploadImage(selector) {
    let input_id = "#picture_image"
    $(selector).on('click', function() {
      let input = $(input_id)
      input.click()
    })

    $(input_id).on('change',function() {
      $('.js-picture-submit').click()
    })
  }

  window.uploadPictureCallBack = function(url) {

    $(".cke_dialog_tabs a.cke_dialog_tab")[0].click()  // 选中 第一个 tab
    $($("input.cke_dialog_ui_input_text")[0]).val(url)
  }

  $(function() {
    checkUploadButton("a.cke_dialog_ui_fileButton.cke_dialog_ui_button")
  });

app/views/hecms/application/_form_error_explanation.html.erb
<% if item.errors.any?%>
  <div class="ui error message">
    <div class="header">
      = t('common.x_errors_count', x: item.errors.count)
    </div>
    <div class="ui clearing divider"></div>
    <ul class="list">
      <% item.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <%end%>
    </ul>
  </div>
<%end%>

app/views/hecms/application/_header.html.erb
  <nav class="fixed top-0 left-0 z-20 h-full pb-10 overflow-x-hidden overflow-y-auto transition origin-left transform bg-white border-r w-60 md:translate-x-0" :class="{ '-translate-x-full' : !sideBar, 'translate-x-0' : sideBar }" @click.away="sideBar = false" >
     <a href="/" class="flex items-center px-4 py-5"> <img src="/brand/kutty-logo.png" alt="Kutty Logo" class="w-20" /> </a> 
     <nav class="text-sm font-medium text-gray-600" aria-label="Main Navigation">
        <a class="flex items-center px-4 py-3 transition cursor-pointer group hover:bg-gray-100 hover:text-gray-900" href="#">
           <svg class="flex-shrink-0 w-5 h-5 mr-2 text-gray-400 transition group-hover:text-gray-600" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
              <path d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z" />
           </svg>
           <span>Home</span> 
        </a>
        <a class="flex items-center px-4 py-3 transition cursor-pointer group hover:bg-gray-100 hover:text-gray-900" href="#">
           <svg class="flex-shrink-0 w-5 h-5 mr-2 text-gray-400 transition group-hover:text-gray-600" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
              <path d="M5 3a1 1 0 000 2c5.523 0 10 4.477 10 10a1 1 0 102 0C17 8.373 11.627 3 5 3z" />
              <path d="M4 9a1 1 0 011-1 7 7 0 017 7 1 1 0 11-2 0 5 5 0 00-5-5 1 1 0 01-1-1zM3 15a2 2 0 114 0 2 2 0 01-4 0z" />
           </svg>
           <span>Articles</span> 
        </a>
        <a class="flex items-center px-4 py-3 text-gray-900 transition bg-gray-100 cursor-pointer group hover:bg-gray-100 hover:text-gray-900" href="#">
           <svg class="flex-shrink-0 w-5 h-5 mr-2 text-gray-600 transition group-hover:text-gray-600" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
              <path d="M7 3a1 1 0 000 2h6a1 1 0 100-2H7zM4 7a1 1 0 011-1h10a1 1 0 110 2H5a1 1 0 01-1-1zM2 11a2 2 0 012-2h12a2 2 0 012 2v4a2 2 0 01-2 2H4a2 2 0 01-2-2v-4z" />
           </svg>
           <span>Collections</span> 
        </a>
        <a class="flex items-center px-4 py-3 transition cursor-pointer group hover:bg-gray-100 hover:text-gray-900" href="#">
           <svg class="flex-shrink-0 w-5 h-5 mr-2 text-gray-400 transition group-hover:text-gray-600" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
              <path d="M9 2a1 1 0 000 2h2a1 1 0 100-2H9z" />
              <path fill-rule="evenodd" d="M4 5a2 2 0 012-2 3 3 0 003 3h2a3 3 0 003-3 2 2 0 012 2v11a2 2 0 01-2 2H6a2 2 0 01-2-2V5zm9.707 5.707a1 1 0 00-1.414-1.414L9 12.586l-1.293-1.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
           </svg>
           <span>Checklists</span> 
        </a>
        <div x-data="collapse()">
           <div class="flex items-center justify-between px-4 py-3 transition cursor-pointer group hover:bg-gray-100 hover:text-gray-900" role="button" x-spread="trigger">
              <div class="flex items-center">
                 <svg class="flex-shrink-0 w-5 h-5 mr-2 text-gray-400 transition group-hover:text-gray-600" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                    <path fill-rule="evenodd" d="M12.316 3.051a1 1 0 01.633 1.265l-4 12a1 1 0 11-1.898-.632l4-12a1 1 0 011.265-.633zM5.707 6.293a1 1 0 010 1.414L3.414 10l2.293 2.293a1 1 0 11-1.414 1.414l-3-3a1 1 0 010-1.414l3-3a1 1 0 011.414 0zm8.586 0a1 1 0 011.414 0l3 3a1 1 0 010 1.414l-3 3a1 1 0 11-1.414-1.414L16.586 10l-2.293-2.293a1 1 0 010-1.414z" clip-rule="evenodd" />
                 </svg>
                 <span>Integrations</span> 
              </div>
              <svg :class="{ 'rotate-90': open }" class="flex-shrink-0 w-4 h-4 ml-2 transition transform" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                 <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
              </svg>
           </div>
           <div class="mb-4" x-spread="collapse" x-cloak> <a class="flex items-center py-2 pl-12 pr-4 transition cursor-pointer hover:bg-gray-100 hover:text-gray-900" href="#">Shopify</a> <a class="flex items-center py-2 pl-12 pr-4 transition cursor-pointer hover:bg-gray-100 hover:text-gray-900" href="#">Slack</a> <a class="flex items-center py-2 pl-12 pr-4 transition cursor-pointer hover:bg-gray-100 hover:text-gray-900" href="#">Zapier</a> </div>
        </div>
        <a class="flex items-center px-4 py-3 transition cursor-pointer group hover:bg-gray-100 hover:text-gray-900" href="#">
           <svg class="flex-shrink-0 w-5 h-5 mr-2 text-gray-400 transition group-hover:text-gray-600" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M5 5a3 3 0 015-2.236A3 3 0 0114.83 6H16a2 2 0 110 4h-5V9a1 1 0 10-2 0v1H4a2 2 0 110-4h1.17C5.06 5.687 5 5.35 5 5zm4 1V5a1 1 0 10-1 1h1zm3 0a1 1 0 10-1-1v1h1z" clip-rule="evenodd" />
              <path d="M9 11H3v5a2 2 0 002 2h4v-7zM11 18h4a2 2 0 002-2v-5h-6v7z" />
           </svg>
           <span>Changelog</span> 
        </a>
        <a class="flex items-center px-4 py-3 transition cursor-pointer group hover:bg-gray-100 hover:text-gray-900" href="#">
           <svg class="flex-shrink-0 w-5 h-5 mr-2 text-gray-400 transition group-hover:text-gray-600" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M11.49 3.17c-.38-1.56-2.6-1.56-2.98 0a1.532 1.532 0 01-2.286.948c-1.372-.836-2.942.734-2.106 2.106.54.886.061 2.042-.947 2.287-1.561.379-1.561 2.6 0 2.978a1.532 1.532 0 01.947 2.287c-.836 1.372.734 2.942 2.106 2.106a1.532 1.532 0 012.287.947c.379 1.561 2.6 1.561 2.978 0a1.533 1.533 0 012.287-.947c1.372.836 2.942-.734 2.106-2.106a1.533 1.533 0 01.947-2.287c1.561-.379 1.561-2.6 0-2.978a1.532 1.532 0 01-.947-2.287c.836-1.372-.734-2.942-2.106-2.106a1.532 1.532 0 01-2.287-.947zM10 13a3 3 0 100-6 3 3 0 000 6z" clip-rule="evenodd" />
           </svg>
           <span>Settings</span> 
        </a>
     </nav>
  </nav>

app/views/hecms/application/_index_actions.html.erb
<%
  show = show
  edit = edit
  delete = delete
  restore = restore
%>


<% if show.present? %>
  <%= link_to t('common.show'), show, class: "ui tiny basic button" %>
<%end%>
<% if edit.present? %>
  <%= link_to t('common.edit'), edit, class: "ui tiny button" %>
<%end%>
<% if delete.present? %>
  <%= link_to t('common.delete'), delete, class: "ui tiny inverted red button", method: :delete, data: { confirm: t('common.are_you_sure_to_delete')} %>
<%end%>
<% if restore.present? %>
  <%= link_to t('common.restore'), restore,class: "ui basic tiny green button", method: :patch, data: { confirm: t('common.are_you_sure_to_restore') } %>
<%end%>

app/views/hecms/application/_index_toolbar.html.erb
<% if new_path.present? && (action_name == 'index') %>
  <%= link_to t('common.new'), new_path, class: "ui right floated basic button" %>
<%end%>
<% if search_path.present? %>
  <%= form_tag search_path, method: :get do %>
    <%= link_to t('common.list_all'), search_path.split('?')[0], class: 'ui basic button' %>
    <div class="ui action input" >
      <%= text_field_tag :keyword, params[:keyword] %>
      <button class="ui iconbutton">
        <i class="search icon"></i>
      </button>
    </div>
  <%end%>
<%end%>

app/views/hecms/application/_table_pagination_foot.html.erb
<tfoot>
  <tr>
    <th colspan="<%= colspan%>">
      <% if items.total_pages > 1 %>
        <div class="ui right floated pagination menu">
          <%= paginate items, window: 2, views_prefix: 'adm' %>
        </div>
      <%end%>
      <a class="ui large basic button" href="<%= request.url %>">
        <%= t('common.total_x_pages_y_count', x: items.total_pages, y: items.total_count) %>
      </a>
    </th>
  </tr>
<tfoot>